In [1]:
import os
import pickle
import argparse

import torch
import torch.nn as nn

from slurp_embeddings_and_targets import SLURPEmbeddingsTargets

In [2]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Running on", device)

Running on cuda


In [3]:
folder = "extracted/speecht5"
modality = "text"
split = "train"

In [4]:
train_set = SLURPEmbeddingsTargets(folder, modality, split)

In [5]:
len(train_set)

11514

In [7]:
len(train_set.intents)

AttributeError: 'SLURPEmbeddingsTargets' object has no attribute 'intents'

In [8]:
from slurp_data import SLURPDataset

In [9]:
slurp_dataset = SLURPDataset("slurp", mode="train", task="intent")

In [10]:
len(slurp_dataset)

11514

In [11]:
len(slurp_dataset.intents)

91

In [12]:
slurp_dataset.intents

['calendar_query',
 'general_joke',
 'music_settings',
 'sendemail',
 'music',
 'hue_lightdim',
 'lists_createoradd',
 'music_query',
 'play_podcasts',
 'quirky',
 'calendar_set',
 'lists_query',
 'music_dislikeness',
 'datetime_convert',
 'coffee',
 'recommendation_movies',
 'events',
 'calendar_remove',
 'currency',
 'greet',
 'iot_hue_lightoff',
 'email_query',
 'transport_traffic',
 'takeaway_query',
 'set',
 'querycontact',
 'transport_ticket',
 'alarm_remove',
 'wemo_on',
 'hue_lightoff',
 'iot_wemo_off',
 'play_audiobook',
 'qa_currency',
 'news_query',
 'play_radio',
 'qa_factoid',
 'traffic',
 'qa_maths',
 'createoradd',
 'cleaning',
 'joke',
 'cooking_query',
 'factoid',
 'audio_volume_mute',
 'radio',
 'addcontact',
 'query',
 'audio_volume_up',
 'definition',
 'iot_hue_lightchange',
 'wemo_off',
 'iot_hue_lightup',
 'general_greet',
 'volume_other',
 'podcasts',
 'play_game',
 'audio_volume_down',
 'iot_cleaning',
 'email_addcontact',
 'ticket',
 'datetime_query',
 'iot_wem

In [6]:
slurp_id, embedding, target = test_set[0]

In [7]:
slurp_id

12717

In [8]:
embedding.shape

torch.Size([30, 768])

In [9]:
target

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 0])

In [10]:
a = torch.tensor([[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]], dtype=torch.float32)
print(a.shape)
print(a)

torch.Size([1, 3, 5])
tensor([[[ 1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10.],
         [11., 12., 13., 14., 15.]]])


In [11]:
simple = torch.mean(a, dim=1, keepdim=True)
print(simple.shape)
print(simple)

torch.Size([1, 1, 5])
tensor([[[ 6.,  7.,  8.,  9., 10.]]])


In [12]:
b = torch.max(a, dim=1, keepdim=True).values
print(b.shape)
print(b)

torch.Size([1, 1, 5])
tensor([[[11., 12., 13., 14., 15.]]])


In [13]:
self_attention = nn.MultiheadAttention(5, 1, batch_first=True)
out, weights = self_attention(a,a,a)

In [14]:
out.shape

torch.Size([1, 3, 5])

In [15]:
out

tensor([[[-1.9226, -0.3444, -0.3757, -1.1616, -2.6338],
         [-2.3999, -0.5425, -0.4834, -1.5370, -3.1808],
         [-2.8577, -0.7326, -0.5867, -1.8971, -3.7055]]],
       grad_fn=<TransposeBackward0>)

In [16]:
weights.shape

torch.Size([1, 3, 3])

In [17]:
weights

tensor([[[0.4986, 0.3094, 0.1920],
         [0.3073, 0.3326, 0.3601],
         [0.1549, 0.2926, 0.5525]]], grad_fn=<MeanBackward1>)