In [1]:
import os
import pickle
import argparse

import torch
import torch.nn as nn

from slurp_embeddings_and_targets import SLURPEmbeddingsTargets

In [2]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Running on", device)

Running on cuda


In [3]:
folder = "extracted/speecht5"
modality = "text"
split = "train"

In [4]:
train_set = SLURPEmbeddingsTargets(folder, modality, split)

In [5]:
len(train_set)

11514

In [7]:
len(train_set.intents)

AttributeError: 'SLURPEmbeddingsTargets' object has no attribute 'intents'

In [8]:
from slurp_data import SLURPDataset

In [9]:
slurp_dataset = SLURPDataset("slurp", mode="train", task="intent")

In [10]:
len(slurp_dataset)

11514

In [11]:
len(slurp_dataset.intents)

91

In [12]:
slurp_dataset.intents

['calendar_query',
 'general_joke',
 'music_settings',
 'sendemail',
 'music',
 'hue_lightdim',
 'lists_createoradd',
 'music_query',
 'play_podcasts',
 'quirky',
 'calendar_set',
 'lists_query',
 'music_dislikeness',
 'datetime_convert',
 'coffee',
 'recommendation_movies',
 'events',
 'calendar_remove',
 'currency',
 'greet',
 'iot_hue_lightoff',
 'email_query',
 'transport_traffic',
 'takeaway_query',
 'set',
 'querycontact',
 'transport_ticket',
 'alarm_remove',
 'wemo_on',
 'hue_lightoff',
 'iot_wemo_off',
 'play_audiobook',
 'qa_currency',
 'news_query',
 'play_radio',
 'qa_factoid',
 'traffic',
 'qa_maths',
 'createoradd',
 'cleaning',
 'joke',
 'cooking_query',
 'factoid',
 'audio_volume_mute',
 'radio',
 'addcontact',
 'query',
 'audio_volume_up',
 'definition',
 'iot_hue_lightchange',
 'wemo_off',
 'iot_hue_lightup',
 'general_greet',
 'volume_other',
 'podcasts',
 'play_game',
 'audio_volume_down',
 'iot_cleaning',
 'email_addcontact',
 'ticket',
 'datetime_query',
 'iot_wem

In [6]:
slurp_id, embedding, target = test_set[0]

In [7]:
slurp_id

12717

In [8]:
embedding.shape

torch.Size([30, 768])

In [9]:
target

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 0])

In [3]:
a = torch.tensor([[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]], dtype=torch.float32)
print(a.shape)
print(a)

torch.Size([1, 3, 5])
tensor([[[ 1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10.],
         [11., 12., 13., 14., 15.]]])


In [4]:
simple = torch.mean(a, dim=1, keepdim=True)
print(simple.shape)
print(simple)

torch.Size([1, 1, 5])
tensor([[[ 6.,  7.,  8.,  9., 10.]]])


In [5]:
b = torch.max(a, dim=1, keepdim=True).values
print(b.shape)
print(b)

torch.Size([1, 1, 5])
tensor([[[11., 12., 13., 14., 15.]]])


In [6]:
self_attention = nn.MultiheadAttention(5, 1, batch_first=True)
out, weights = self_attention(a,a,a)

In [7]:
out.shape

torch.Size([1, 3, 5])

In [8]:
out

tensor([[[-7.0852, -3.5816, -2.0198,  8.8040, -1.0637],
         [-7.0907, -3.5845, -2.0220,  8.8127, -1.0643],
         [-7.0907, -3.5845, -2.0220,  8.8127, -1.0643]]],
       grad_fn=<TransposeBackward0>)

In [9]:
weights.shape

torch.Size([1, 3, 3])

In [10]:
weights

tensor([[[5.0034e-06, 2.2343e-03, 9.9776e-01],
         [1.5852e-15, 3.9815e-08, 1.0000e+00],
         [5.0113e-25, 7.0790e-13, 1.0000e+00]]], grad_fn=<MeanBackward1>)

In [23]:
a.shape

torch.Size([1, 3, 5])

In [12]:
a

tensor([[[ 1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10.],
         [11., 12., 13., 14., 15.]]])

In [24]:
aa = a.squeeze(0)
aa.shape

torch.Size([3, 5])

In [35]:
aa.T.shape

torch.Size([5, 3])

In [25]:
q = torch.tensor([[0.1, 0.2, 0.3, 0.4, 0.5]], dtype=torch.float32)
q.shape

torch.Size([1, 5])

In [26]:
q

tensor([[0.1000, 0.2000, 0.3000, 0.4000, 0.5000]])

In [33]:
g = torch.matmul(q, aa.T)

In [34]:
g.shape

torch.Size([1, 3])

In [20]:
a.T.shape

torch.Size([5, 3, 1])

In [38]:
z = nn.Softmax(dim=1)(g)
z.shape

torch.Size([1, 3])

In [40]:
new_x = torch.matmul(z, aa)
new_x.shape

torch.Size([1, 5])

In [45]:
a = torch.cat([a,a])

In [46]:
a.shape, q.shape

(torch.Size([2, 3, 5]), torch.Size([1, 5]))

In [50]:
o1 = torch.matmul(a, q.T)

In [51]:
o1.shape

torch.Size([2, 3, 1])

In [53]:
o1, g

(tensor([[[ 5.5000],
          [13.0000],
          [20.5000]],
 
         [[ 5.5000],
          [13.0000],
          [20.5000]]]),
 tensor([[ 5.5000, 13.0000, 20.5000]]))

In [58]:
x2 = torch.matmul(o1.permute(0, 2, 1), a)

In [60]:
x2.shape

torch.Size([2, 1, 5])

In [59]:
x2, (g@aa)

(tensor([[[309., 348., 387., 426., 465.]],
 
         [[309., 348., 387., 426., 465.]]]),
 tensor([[309., 348., 387., 426., 465.]]))